Real_Estate/Models/Appointment.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace Real_Estate.Models
{
    public class Appointment
    {
        public int Id { get; set; }
        public string ClientId { get; set; }
        [ValidateNever]
        public ApplicationUser? Clients { get; set; }
        public string OwnerId { get; set; }
        [ValidateNever]
        public ApplicationUser? Owners { get; set; }
        public int OwnerScheduleId { get; set; }
        [ValidateNever]
        public OwnerSchedule? OwnerSchedules { get; set; }
        public int EstatePropertyId { get; set; }

        [ValidateNever]
        public EstateProperty? EstateProperty { get; set; }
        //authit trail
        public DateTime? CreationDate { get; set; } = DateTime.Now;
    }
}

Real_Estate/ViewModels/CreateAppointmentViewModel.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Real_Estate.Models;
using System.ComponentModel.DataAnnotations;

namespace Real_Estate.ViewModels
{
    public class CreateAppointmentViewModel
    {
        [Required]
        public int OwnerScheduleId { get; set; }

        [Required]
        public int EstatePropertyId { get; set; }

        [ValidateNever]
        public OwnerSchedule OwnerSchedule { get; set; }

        [ValidateNever]
        public EstateProperty EstateProperty { get; set; }
    }
}

Real_Estate/Controllers/AppointmentsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Real_Estate.Repository.Appointments;
using Real_Estate.Data;
using Real_Estate.Models;
using Real_Estate.ViewModels;
using System.Security.Claims;
using Real_Estate.Repository.OwnerSchedules;
using Real_Estate.Repository.EstateProperties;

namespace Real_Estate.Controllers
{
    [Authorize]
    public class AppointmentController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IAppointmentRepository _appointmentRepository;
        private readonly IOwnerScheduleRepository _ownerScheduleRepository;
        private readonly IEstatePropertyRepository _estatePropertyRepository;
        private RealEDbContext _context;

        public AppointmentController(UserManager<ApplicationUser> userManager, 
                                        RealEDbContext context, 
                                        IAppointmentRepository appointmentRepository, 
                                        IOwnerScheduleRepository ownerScheduleRepository,
                                        IEstatePropertyRepository estatePropertyRepository)
        {
            _userManager = userManager;
            _context = context;
            this._appointmentRepository = appointmentRepository;
            this._ownerScheduleRepository = ownerScheduleRepository;
            this._estatePropertyRepository = estatePropertyRepository;
        }

        public IActionResult DeleteConfirmation()
        {
            return View();
        }

        public async Task<IActionResult> Index()
        {
            string currentlyLoggedInUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ApplicationUser? currentlyLoggedInUser = await _context.ApplicationUsers.FindAsync(currentlyLoggedInUserId);
            var currentlyLoggedInUserRoles = await _userManager.GetRolesAsync(currentlyLoggedInUser);

            var appointmentList = await this._appointmentRepository.GetAppointmentsByIdAndUserRole(
                currentlyLoggedInUser.Id,
                currentlyLoggedInUserRoles.First()
            );

            return View(appointmentList);
        }

        [HttpGet]
        public async Task<IActionResult> CreateAppointment(int ownerScheduleId, int propertyId)
        {
            OwnerSchedule ownerSchedule = await this._ownerScheduleRepository
                .GetOwnerScheduleById(ownerScheduleId);

            EstateProperty estateProperty = await this._estatePropertyRepository
                .GetEstatePropertyById(propertyId);

            CreateAppointmentViewModel createAppointmentViewModel = new CreateAppointmentViewModel()
            {
                OwnerScheduleId = ownerScheduleId,
                EstatePropertyId = propertyId,
                OwnerSchedule = ownerSchedule,
                EstateProperty = estateProperty
            };

            return View(createAppointmentViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> CreateAppointment(CreateAppointmentViewModel appointment)
        {
            if (!ModelState.IsValid)
            {
                return View(appointment);
            }

            string clientId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            EstateProperty property = await this._estatePropertyRepository
                .GetEstatePropertyById(appointment.EstatePropertyId);
            ApplicationUser? client = await _context.ApplicationUsers.FindAsync(clientId);

            await this._appointmentRepository.AddAppointment(client.Id, property.ApplicationUserId, appointment);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> GetPropertyAppointments(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var property = await this._estatePropertyRepository.GetEstatePropertyWithUserById(id);

            if (property == null)
            {
                return NotFound();
            }

            var ownerSchedules = await this._ownerScheduleRepository
                .GetOwnerScheduleByPropertyIdAndOwnerId(id, property.ApplicationUserId);

            return View(ownerSchedules);
        }

        [HttpPost]
        public async Task<IActionResult> GetPropertyAppointments(Appointment appointment)
        {
            if (ModelState.IsValid)
            {
                await this._appointmentRepository.AddAppointment(appointment);
                return RedirectToAction(nameof(GetPropertyAppointments), new { id = appointment.EstatePropertyId });
            }
            return View(appointment);
        }
        
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            Appointment appointment = await this._appointmentRepository.GetAppointmentById(id);

            if (appointment == null)
            {
                return NotFound();
            }

            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (appointment.ClientId != userId && appointment.OwnerId != userId)
            {
                return Forbid();
            }

            return View(appointment);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await this._appointmentRepository.DeleteAppointmentById(id);
            return RedirectToAction("Index");
        }
    }
}

Real_Estate/Views/Appointment/CreateAppointment.cshtml
@model CreateAppointmentViewModel
<div class="text-white">
<h2>Create Appointment</h2>

<form asp-action="CreateAppointment" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input asp-for="OwnerScheduleId" value="@Model.OwnerScheduleId" hidden/>
    <input asp-for="EstatePropertyId" value="@Model.EstatePropertyId" hidden/>
    <div>
        Owner Schedule: @(Model.OwnerSchedule.startTime) - @(Model.OwnerSchedule.endTime)
    </div>
    <table>
        <thead>
            <tr>
                <td>Property Name</td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.EstateProperty.Name</td>
            </tr>
        </tbody>
    </table>

    <button type="submit" class="btn btn-primary">Create</button>
</form>
</div>

Real_Estate/Views/Appointment/Delete.cshtml
@model Appointment



<div class="d-flex justify-content-center">
    <div class="card-box ">
        <h4>Are you sure you want to delete this appointment?</h4>
<form asp-action="DeleteConfirmed" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group d-flex">
        <input type="submit" value="Yes" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-secondary">No</a>
    </div>
</form>
</div>
</div>
<style>
    .card-box {
        width: 400px;
        background-color: #fff;
        border: 1px solid #ddd;
        border-radius: 5px;
        padding: 20px;
        text-align: center;
    }

    .success-icon {
        color: #28a745;
        font-size: 48px;
        margin-bottom: 20px;
    }

    .btn {
        background-color: #F4A424;
        color: #fff;
        border: none;
        border-radius: 5px;
        padding: 10px 20px;
        font-size: 16px;
        cursor: pointer;
        width:50%;
        margin:10px;

    }

        .btn:hover {
            background-color: #0062cc;
        }

</style>
<script>
    function showSuccessMessage() {
        var cardBox = document.querySelector(".card-box");
        cardBox.style.display = "block";
    }

    // Code to hide the card box message
    function hideSuccessMessage() {
        var cardBox = document.querySelector(".card-box");
        cardBox.style.display = "none";
    }
</script>

Real_Estate/Views/Appointment/DeleteConfirmation.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="d-flex justify-content-center">
    <div class="card-box " >
    <h2 class="text-white">Confirm Deletion</h2>

        <p class="text-white">Are you sure you want to Cancel this appointment?</p>

<form asp-action="Delete" asp-route-id="@Model.Id" method="post">
    <input type="submit" value="Yes" class="btn btn-danger" />
    <a asp-action="Index" class="btn btn-secondary" style="color: #000;">>No</a>
</form>
    </div>
</div>
<style>
   .card-box {
  width: 400px;
  background-color: #fff;
  border: 1px solid #ddd;
  border-radius: 5px;
  padding: 20px;
  text-align: center;
}

.success-icon {
  color: #28a745;
  font-size: 48px;
  margin-bottom: 20px;
}

.btn {
  background-color: #007bff;
  color: #fff;
  border: none;
  border-radius: 5px;
  padding: 10px 20px;
  font-size: 16px;
  cursor: pointer;
}

.btn:hover {
  background-color: #0062cc;
}

</style>
<script>
    function showSuccessMessage() {
  var cardBox = document.querySelector(".card-box");
  cardBox.style.display = "block";
}

// Code to hide the card box message
function hideSuccessMessage() {
  var cardBox = document.querySelector(".card-box");
  cardBox.style.display = "none";
}
</script>

Real_Estate/Views/Appointment/GetPropertyAppointments.cshtml
@model List<EventViewModel>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Property Appointments";
}
<h2 class="text-center mb-4 text-black">@ViewData["Title"]</h2>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <style>
        * {
            font-family: 'Outfit', sans-serif;
        }
    </style>
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.5/index.global.min.js'></script>
</head>
<body>
    <div id="calendar"></div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script>
         var events = @Html.Raw(Json.Serialize(Model))

            document.addEventListener('DOMContentLoaded', function () {

            @*var modalEl = document.getElementById('modal');
                    var modal = new bootstrap.Modal(modalEl);*@
                var calendarEl = document.getElementById('calendar');
                var calendar = new FullCalendar.Calendar(calendarEl, {
                    initialView: 'dayGridMonth',
                   events: events,
                    dateClick: function (info) {
                        window.open(info.event.url)
                    }
                });

                calendar.render();

                calendar.on('dateClick', function (info) {
                    var button = document.createElement('button');
                    button.setAttribute('data-date', info.dateStr);
                    modal.show(button);
                })

                modalEl.addEventListener('show.bs.modal', function (e) {
                    var form = this.querySelector('form');
                    form.date.value = e.relatedTarget.getAttribute('data-date');

                })

                calendar.add
            })
    </script>
</body>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Real_Estate/Views/Appointment/Index.cshtml
@model List<Appointment>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Appointment List";
}
@*<h2 class="text-center mb-4 text-white">@ViewData["Title"]</h2>*@
<h1 class="whiteText" style="text-align: center;">Appointment List</h1>
<style>
    h2 {
        text-align: center;
        padding: 20px 0;
    }

    .table-bordered {
        border: 1px solid #ddd !important;
    }

    table caption {
        padding: .5em 0;
    }

    table caption {
        display: none;
    }

    .p {
        text-align: center;
        padding-top: 140px;
        font-size: 14px;
    }

    td {
        color: #fff;
    }

    th {
        color: #fff;
    }
</style>
<table>
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="table-responsive" data-pattern="priority-columns">
                    <table class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>Client Name</th>
                                <th>Property Name</th>
                                <th>Schedule</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Clients.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.EstateProperty.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.OwnerSchedules.startTime)
                                        @Html.DisplayFor(modelItem => item.OwnerSchedules.endTime)

                                    </td>
                                    <td>
                                        <a class="btn btn-danger" asp-controller="Appointment" title="DeleteSchedule" asp-action="Delete" asp-route-Id="@item.Id">
                                            <i class="fas fa-user-times"></i>
                                        </a>

                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div><!--end of .table-responsive-->
            </div>
        </div>
    </div>
</table>