Real_Estate/Models/SaleorRentModel.cs
namespace Real_Estate.Models
{
    public class SaleorRentModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<EstateProperty>? EstateProperties { get; set; }
    }
}

Real_Estate/Controllers/SaleorRentModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Real_Estate.Data;
using Real_Estate.Models;

namespace Real_Estate.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SaleorRentModelsController : Controller
    {
        private readonly RealEDbContext _context;

        public SaleorRentModelsController(RealEDbContext context)
        {
            _context = context;
        }

        // GET: SaleorRentModels
        public async Task<IActionResult> Index()
        {
            return _context.SaleorRentModel != null ?
                        View(await _context.SaleorRentModel.ToListAsync()) :
                        Problem("Entity set 'RealEDbContext.SaleorRentModel'  is null.");
        }

        // GET: SaleorRentModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.SaleorRentModel == null)
            {
                return NotFound();
            }

            var saleorRentModel = await _context.SaleorRentModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (saleorRentModel == null)
            {
                return NotFound();
            }

            return View(saleorRentModel);
        }

        // GET: SaleorRentModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SaleorRentModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] SaleorRentModel saleorRentModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(saleorRentModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(saleorRentModel);
        }

        // GET: SaleorRentModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.SaleorRentModel == null)
            {
                return NotFound();
            }

            var saleorRentModel = await _context.SaleorRentModel.FindAsync(id);
            if (saleorRentModel == null)
            {
                return NotFound();
            }
            return View(saleorRentModel);
        }

        // POST: SaleorRentModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] SaleorRentModel saleorRentModel)
        {
            if (id != saleorRentModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(saleorRentModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SaleorRentModelExists(saleorRentModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(saleorRentModel);
        }

        // GET: SaleorRentModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.SaleorRentModel == null)
            {
                return NotFound();
            }

            var saleorRentModel = await _context.SaleorRentModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (saleorRentModel == null)
            {
                return NotFound();
            }

            return View(saleorRentModel);
        }

        // POST: SaleorRentModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.SaleorRentModel == null)
            {
                return Problem("Entity set 'RealEDbContext.SaleorRentModel'  is null.");
            }
            var saleorRentModel = await _context.SaleorRentModel.FindAsync(id);
            if (saleorRentModel != null)
            {
                _context.SaleorRentModel.Remove(saleorRentModel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SaleorRentModelExists(int id)
        {
            return (_context.SaleorRentModel?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Real_Estate/Views/SaleorRentModels/Create.cshtml
@model Real_Estate.Models.SaleorRentModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>SaleorRentModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Real_Estate/Views/SaleorRentModels/Delete.cshtml
@model Real_Estate.Models.SaleorRentModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SaleorRentModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Real_Estate/Views/SaleorRentModels/Details.cshtml
@model Real_Estate.Models.SaleorRentModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>SaleorRentModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Real_Estate/Views/SaleorRentModels/Edit.cshtml
@model Real_Estate.Models.SaleorRentModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Edit</h1>

<h4>SaleorRentModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Real_Estate/Views/SaleorRentModels/Index.cshtml
@model IEnumerable<Real_Estate.Models.SaleorRentModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Sale or Rent</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
                <td>
                    <button><a asp-controller="SaleorRentModels" asp-action="Edit" asp-route-id="@item.Id" class="black-text-button"><i class="fas fa-edit"></i></a></button>
                    <button><a asp-controller="SaleorRentModels" asp-action="Details" asp-route-id="@item.Id" class="black-text-button"><i class="far fa-file-alt"></i></a></button>
                    <button><a asp-controller="SaleorRentModels" asp-action="Delete" asp-route-id="@item.Id" class="black-text-button"><i class="fas fa-trash-alt"></i></a></button>
                </td>
        </tr>
}
    </tbody>
</table>